version: "3"

services:
  # database service
  database:
    build:
      context: .
      dockerfile: ./docker/dockerfile_database
    ports:
      - 5432:5432
   
  # backend service getting env parameters from file and executing migrations and runserver
  backend:
    build:
      context: .
      dockerfile: ./docker/dockerfile_backend
    ports:
      - 8000:8000
    depends_on:
      - database
    env_file:
      - ./library_back/renan.env
    command: >
      bash -c "python3 manage.py makemigrations
      && python3 manage.py migrate
      && python3 manage.py runserver 0.0.0.0:8000"

  # frontend service
  frontend:
    container_name: frontend-dev
    build:
      context: ./library_front
      dockerfile: ../docker/dockerfile_frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
